// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUa3YcouizIWnD4Ss987oOOkloppVwkwo',
    appId: '1:621286694030:web:fc2d6ca407077007c27ddf',
    messagingSenderId: '621286694030',
    projectId: 'smait-3bd28',
    authDomain: 'smait-3bd28.firebaseapp.com',
    storageBucket: 'smait-3bd28.firebasestorage.app',
    measurementId: 'G-S7JTQ177D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5IqKwcUye6XQC_kWtlA-a36vadoqF48',
    appId: '1:621286694030:android:0a1cd1da60528677c27ddf',
    messagingSenderId: '621286694030',
    projectId: 'smait-3bd28',
    storageBucket: 'smait-3bd28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADKYEpXK-SKT8ThuT_JFEO_4cVdOLBis',
    appId: '1:621286694030:ios:8f14236ab8344a00c27ddf',
    messagingSenderId: '621286694030',
    projectId: 'smait-3bd28',
    storageBucket: 'smait-3bd28.firebasestorage.app',
    iosBundleId: 'com.example.smait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADKYEpXK-SKT8ThuT_JFEO_4cVdOLBis',
    appId: '1:621286694030:ios:8f14236ab8344a00c27ddf',
    messagingSenderId: '621286694030',
    projectId: 'smait-3bd28',
    storageBucket: 'smait-3bd28.firebasestorage.app',
    iosBundleId: 'com.example.smait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUa3YcouizIWnD4Ss987oOOkloppVwkwo',
    appId: '1:621286694030:web:83ad3671e56c7033c27ddf',
    messagingSenderId: '621286694030',
    projectId: 'smait-3bd28',
    authDomain: 'smait-3bd28.firebaseapp.com',
    storageBucket: 'smait-3bd28.firebasestorage.app',
    measurementId: 'G-ZDGG05ZPS0',
  );
}
